services:
  food-agent:
    build: .
    ports:
      - "7860:7860"
    env_file:
      - .env
    environment:
    - VECTOR_DB_DIR=/app/off_db
    - GRADIO_SERVER_NAME=0.0.0.0
    - MODEL_NAME=claude-sonnet-4-5
    volumes:
      - ./off_db:/app/off_db